/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.Verifierone;
import model.Verifiertwo;
import model.Vitals;

/**
 *
 * @author RaghavGoswami
 */
public class EditPerson extends javax.swing.JPanel {

    /**
     * Creates new form EditPerson
     */
    Vitals vitalsigns;
    Person person;
    private JPanel userProcessor;
    
    public EditPerson(JPanel userProcessor,  Person person) {
        
        this.vitalsigns = vitalsigns;
        this.userProcessor = userProcessor;
        this.person = person;
        initComponents();
        populatePatientDetails();
        addVerifiers();
    }

     private void addVerifiers() {
        InputVerifier integerVerifier = new Verifierone();
        patnotf1.setInputVerifier(integerVerifier);
        patcodetf1.setInputVerifier(integerVerifier);
        patagetf1.setInputVerifier(integerVerifier);
        InputVerifier stringVerifier = new Verifiertwo();
        patnametf1.setInputVerifier(stringVerifier);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        patnametf1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        patagetf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        patnotf1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        patcodetf1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        commcmbbx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        housecmbbx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        citycmbbx = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();

        jLabel10.setForeground(java.awt.Color.blue);
        jLabel10.setText("Name");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        patnametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patnametf1ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(java.awt.Color.blue);
        jLabel11.setText("Age");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setForeground(java.awt.Color.blue);
        jLabel12.setText("Contact Number");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setForeground(java.awt.Color.blue);
        jLabel13.setText("Zipcode");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Community");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        commcmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community1", "Community2" }));
        commcmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commcmbbxActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setText("House");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        housecmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "House1", "House2" }));

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("City");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        citycmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York", "Arizona", "Texas" }));

        jButton9.setBackground(java.awt.Color.cyan);
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnsave.setBackground(java.awt.Color.cyan);
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patcodetf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patnotf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(housecmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(citycmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patagetf1)
                                    .addComponent(patnametf1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                        .addGap(106, 106, 106)
                        .addComponent(jLabel13)))
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(442, 442, 442))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(patnametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(patnotf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(housecmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(patagetf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(patcodetf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(commcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(citycmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(btnsave))
                .addContainerGap(537, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patnametf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patnametf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patnametf1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        userProcessor.remove(this);
        CardLayout layout = (CardLayout) userProcessor.getLayout();
        layout.previous(userProcessor);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput()) {
            person.setPersonName(patnametf1.getText());
            person.setAge(Integer.parseInt(patagetf1.getText()));
            person.setContactno(Integer.parseInt(patnotf1.getText()));
            person.setZipcode(Integer.parseInt(patcodetf1.getText()));
            person.setCommunity(commcmbbx.getSelectedItem().toString());
            person.setHouse(housecmbbx.getSelectedItem().toString());
            person.setCity(citycmbbx.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Person updated!!");
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void commcmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commcmbbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commcmbbxActionPerformed
private Boolean checkBlankInput() {
        if (patnametf1.getText().length() == 0 || patagetf1.getText().length() == 0 ||patcodetf1.getText().length() == 0 || patcodetf1.getText().length() == 0) {
            return false;
        
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> citycmbbx;
    private javax.swing.JComboBox<String> commcmbbx;
    private javax.swing.JComboBox<String> housecmbbx;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField patagetf1;
    private javax.swing.JTextField patcodetf1;
    private javax.swing.JTextField patnametf1;
    private javax.swing.JTextField patnotf1;
    // End of variables declaration//GEN-END:variables

    private void populatePatientDetails() {
        
        patnametf1.setText(person.getPersonName());
        patagetf1.setText(String.valueOf(person.getAge()));
        patnotf1.setText(String.valueOf(person.getContactno()));
        patcodetf1.setText(String.valueOf(person.getZipcode()));
        commcmbbx.setSelectedItem(person.getCommunity());
        housecmbbx.setSelectedItem(person.getHouse());
        citycmbbx.setSelectedItem(person.getCity());
        
    }
    }

