/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Patient;
import model.Verifierone;
import model.Verifiertwo;
import model.Vitals;

/**
 *
 * @author RaghavGoswami
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    Patient patient;
    private JPanel userProcessor;
    public Report(JPanel up,Patient patient) {
        this.patient = patient;
        this.userProcessor = up;
        initComponents();
        addVerifiers();
    }

     private void addVerifiers() {
        InputVerifier integerVerifier = new Verifierone();
        bptf1.setInputVerifier(integerVerifier);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bptf1 = new javax.swing.JTextField();
        savevitals = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setText("Blood Pressure");

        savevitals.setText("Save");
        savevitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savevitalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(bptf1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addComponent(savevitals))
                .addGap(107, 556, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bptf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(savevitals)
                .addGap(27, 27, 27)
                .addComponent(back)
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessor.remove(this);
        CardLayout layout = (CardLayout) userProcessor.getLayout();
        layout.previous(userProcessor);
    }//GEN-LAST:event_backActionPerformed

    private void savevitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savevitalsActionPerformed
        // TODO add your handling code here:
        try {

           // int heartRate = Integer.parseInt(hrtf1.getText());
            int bloodPressure = Integer.parseInt(bptf1.getText());

            Vitals vitals = patient.getEncounter().createvitals();

           // vitals.setHeart_rate(heartRate);
            vitals.setBlood_pressure(bloodPressure);

            /*Set current date and time as TimeStamp*/
            vitals.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Blood Pressure Added", "Update",
                JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please Enter proper values",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savevitalsActionPerformed

private void clearFields()
{
   
    bptf1.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bptf1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton savevitals;
    // End of variables declaration//GEN-END:variables
}
